version: '2.1'

services:
  runeclan_discord_bot:
    image: riccardorestagno/runeclan_discord_bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - runeclanbot:/opt/runeclanbot/clanfile
volumes:
  runeclanbot:
